### ISSUE TITLE
Agency.demo_gradio.<locals>.bot() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by mzubair-irinatechdigital** [VRSEN/agency-swarm#196]
TypeError: Agency.demo_gradio.<locals>.bot() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\blocks.py", line 2043, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\blocks.py", line 1602, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\utils.py", line 710, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\utils.py", line 704, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\utils.py", line 687, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\Ayesha-\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\utils.py", line 843, in gen_wrapper
    iterator = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
TypeError: Agency.demo_gradio.<locals>.bot() takes 2 positional arguments but 3 were given

**Comment by s0yabean** [comment]
I got this error as well.

**Comment by bonk1t** [comment]
Hi everyone! Thank you for reporting this. The hot fix is to add the third argument in the library: `dropdown`. I’ll address this and merge it.

**Comment by CyberZod** [comment]
> Hi everyone! Thank you for reporting this. The fix is to add the third argument in the library: `dropdown`. I’ll address this and merge it.
> 
> Update: @mzubair-irinatechdigital @s0yabean I've merged the fix, please install from the main branch: `pip install git+https://github.com/VRSEN/agency-swarm.git@main`

Still getting the error

**Comment by bonk1t** [comment]
@CyberZod it was fixed in v0.4.2. Please upgrade.

**Comment by CyberZod** [comment]
Worked ✅
