### ISSUE TITLE
TypeError: Object of type method is not JSON serializable when using Python v3.13.0

### ISSUE THREAD

**Issue by mrdavidlaing** [VRSEN/agency-swarm#198]
A simple Agency Swarm project that works using Python v3.10.16 fails to start with when using Python v3.13.0 with the following error:

```
 python agency.py
Traceback (most recent call last):
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/agency.py", line 8, in <module>
    agency = Agency(
        [assistant],  # Single agent setup
    ...<2 lines>...
        max_prompt_tokens=4000
    )
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/agency_swarm/agency/agency.py", line 134, in __init__
    self._init_agents()
    ~~~~~~~~~~~~~~~~~^^
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/agency_swarm/agency/agency.py", line 858, in _init_agents
    agent.init_oai()
    ~~~~~~~~~~~~~~^^
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/agency_swarm/agents/agent.py", line 250, in init_oai
    self.assistant = self.client.beta.assistants.create(
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        model=self.model,
        ^^^^^^^^^^^^^^^^^
    ...<8 lines>...
        response_format=self.response_format,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/openai/resources/beta/assistants.py", line 146, in create
    return self._post(
           ~~~~~~~~~~^
        "/assistants",
        ^^^^^^^^^^^^^^
    ...<18 lines>...
        cast_to=Assistant,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/openai/_base_client.py", line 1280, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/openai/_base_client.py", line 957, in request
    return self._request(
           ~~~~~~~~~~~~~^
        cast_to=cast_to,
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        retries_taken=retries_taken,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/openai/_base_client.py", line 983, in _request
    request = self._build_request(options, retries_taken=retries_taken)
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/openai/_base_client.py", line 506, in _build_request
    return self._client.build_request(  # pyright: ignore[reportUnknownMemberType]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        headers=headers,
        ^^^^^^^^^^^^^^^^
    ...<10 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/httpx/_client.py", line 378, in build_request
    return Request(
        method,
    ...<8 lines>...
        extensions=extensions,
    )
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/httpx/_models.py", line 408, in __init__
    headers, stream = encode_request(
                      ~~~~~~~~~~~~~~^
        content=content,
        ^^^^^^^^^^^^^^^^
    ...<7 lines>...
        ),
        ^^
    )
    ^
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/httpx/_content.py", line 216, in encode_request
    return encode_json(json)
  File "/Users/mrdavidlaing/workspace/scratchpad/agency-swarm-experiment1/.venv/lib/python3.13/site-packages/httpx/_content.py", line 177, in encode_json
    body = json_dumps(
           ~~~~~~~~~~^
        json, ensure_ascii=False, separators=(",", ":"), allow_nan=False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).encode("utf-8")
    ^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type method is not JSON serializable
```

**Comment by mrdavidlaing** [comment]
As best I can tell it seems to be related to the reference to [tool.openai_schema](https://github.com/VRSEN/agency-swarm/blob/77add5db025f1291ae77cdcb13e3701fb20b27fe/agency_swarm/agents/agent.py#L484) not being compatible with `json.dumps()`; but I'm just guessing.
