### ISSUE TITLE
Task exception was never retrieved error in notebook

### ISSUE THREAD

**Issue by OrwellianOwl** [VRSEN/agency-swarm#43]
Task exception was never retrieved
future: <Task finished name='mwhqygqb27f_1' coro=<Queue.process_events() done, defined at /Users/xx/anaconda3/lib/python3.11/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [[]], 'event_dat...on_hash': 'mwhqygqb27f'}, input_type=dict]
    For further information visit [https://errors.pydantic.dev/2.3/v/missing>](https://errors.pydantic.dev/2.3/v/missing%3E)
Traceback (most recent call last):
  File "/Users/xx/anaconda3/lib/python3.11/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/anaconda3/lib/python3.11/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/anaconda3/lib/python3.11/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/anaconda3/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1
 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [[]], 'event_dat...on_hash': 'mwhqygqb27f'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing

<img width="1126" alt="Screenshot 2024-01-11 at 13 34 14" src="https://github.com/VRSEN/agency-swarm/assets/99193328/98b166c3-04b8-4fa7-b8fb-e5ce2ea5d582">
<img width="999" alt="Screenshot 2024-01-11 at 13 34 22" src="https://github.com/VRSEN/agency-swarm/assets/99193328/bf5ba579-ef3c-48eb-9307-f731c32ef009">

**Comment by OrwellianOwl** [comment]
Hey all, any idea on why this is happening?
