### ISSUE TITLE
ModuleNotFoundError: No module named 'readline'

### ISSUE THREAD

**Issue by MizpahMJP** [VRSEN/agency-swarm#95]
![image](https://github.com/VRSEN/agency-swarm/assets/164722692/ab71b1b2-95c3-4b11-bcf8-b4b93aeb06d4)

getting error on running genesis command
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Scripts\agency-swarm.exe\__main__.py", line 4, in <module>
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\agency_swarm\__init__.py", line 1, in <module>
    from .agency import Agency
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\agency_swarm\agency\__init__.py", line 1, in <module>
    from .agency import Agency
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\agency_swarm\agency\agency.py", line 4, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by VRSEN** [comment]
Seems like this module is not available on windows. Try `pip install pyreadline`. Let me know if this works, please.

**Comment by MizpahMJP** [comment]
This fixed it 
pip install **pyreadline3**
